POST http://127.0.0.1:8000/getphoto
content-type: application/json
Access-Control-Allow-Origin: *

{
    "uid": "",
    "has_been_processed": false,
    "prompt_negative": "",
    "prompt": "",
    "negative_prompt": "",
    "read_wildcards_in_order": false,
    "width": null,
    "height": null,
    "sample_sharpness": 2.0,
    "seed": 7218701886844104775,
    "sampler_name": "dpmpp_2m_sde_gpu",
    "scheduler_name": "karras",
    "base_model_name": "juggernautXL_v8Rundiffusion.safetensors",
    "refiner_model": false,
    "refiner_switch": 0.5,
    "refiner_swap_method": "joint",
    "loras": [
        [
            true,
            "sd_xl_offset_example-lora_1.0.safetensors",
            0.1
        ],
        [
            true,
            "None",
            1.0
        ],
        [
            true,
            "None",
            1.0
        ],
        [
            true,
            "None",
            1.0
        ],
        [
            true,
            "None",
            1.0
        ]
    ],
    "styles": [
        "Fooocus V2",
        "Fooocus Enhance",
        "Fooocus Sharp"
    ],
    "vae_name": "Default (model)",
    "performance_selection": "Speed",
    "performance_loras": [],
    "previous_default_models": [
        "juggernautXL_version8Rundiffusion.safetensors",
        "juggernautXL_version7Rundiffusion.safetensors",
        "juggernautXL_v7Rundiffusion.safetensors",
        "juggernautXL_version6Rundiffusion.safetensors",
        "juggernautXL_v6Rundiffusion.safetensors"
    ],
    "output_format": "webp",
    "save_metadata_to_images": false,
    "save_only_final_enhanced_image": false,
    "aspect_ratio": "1152*896",
    "image_number": 1,
    "steps": -1,
    "original_steps": 0,
    "adaptive_cfg": 7.0,
    "cfg_scale": 4.0,
    "cfg_tsnr": 7.0,
    "adm_scaler_end": 0.3,
    "adm_scaler_negative": 0.8,
    "adm_scaler_positive": 1.5,
    "canny_high_threshold": 128,
    "canny_low_threshold": 64,
    "checkpoint_downloads": {
        "juggernautXL_v8Rundiffusion.safetensors": "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_v8Rundiffusion.safetensors"
    },
    "vae_downloads": {},
    "lora_downloads": {
        "sd_xl_offset_example-lora_1.0.safetensors": "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_offset_example-lora_1.0.safetensors"
    },
    "embeddings_downloads": {},
    "clip_skip": 2,
    "controlnet_softness": 0.25,
    "dino_erode_or_dilate": 0,
    "enhance_task": null,
    "freeu_controls": null,
    "inpaint_options": null,
    "controlnet_tasks": null,
    "overwrite_controls": null,
    "developer_options": {
        "metadata_created_by": "",
        "metadata_scheme": "Hooocus",
        "debugging_cn_preprocessor": false,
        "debugging_dino": false,
        "debugging_enhance_masks_checkbox": false,
        "debugging_inpaint_preprocessor": false,
        "temp_path_cleanup_on_launch": true,
        "temp_path": "/tmp/hooocus",
        "disable_intermediate_results": false,
        "disable_seed_increment": false,
        "generate_grid": false,
        "disable_preview": false,
        "skipping_cn_preprocessor": false,
        "should_use_advanced": false,
        "should_use_developer_debug_mode": false
    },
    "describe_content_type": [
        "Photograph"
    ],
    "use_image_input": false,
    "use_image_prompt_advanced": false,
    "use_imageprompt": false,
    "use_upscale_or_vary": false,
    "mix_image_prompt_and_vary_upscale": false,
    "mix_image_prompt_and_inpaint": false,
    "image_input_mode": "uov",
    "input_image": null,
    "uov_input_image": null,
    "input_mask_image": null,
    "prepared_input_mask_image": null,
    "enhance_input_image": null,
    "uov_method": null,
    "steps_uov": -1
}



